### ISSUE TITLE
Can it send De-Auth Packets too, For speeding up the capture of 4-way-handshakes ?  

### ISSUE THREAD

**Issue by minanagehsalalma** [alexus2033/RTL8720-Sniffer#1]
It's a really cool idea That to sniff using the RTL8720 

And it would be better if you could deauth devices for faster Packets Capturing.

Thanks a lot :)

**Comment by alexus2033** [comment]
I´m not sure if the [RTL8720 SDK](https://github.com/luanxg/RTL8720-SDK/tree/master/component/common/api/wifi) is powerful enough for this kind of attack. Do you know a Code-Snippet as an example?

**Comment by minanagehsalalma** [comment]
> Do you know a Code-Snippet as an example?

Unfortunately no , I mailed [luanxg](https://github.com/luanxg) asking him if it's possible or not , waiting for his answer 

All i know about is [esp8266_deauther](https://github.com/SpacehuhnTech/esp8266_deauther)
